name: Deploy All Lambda Functions by Folder

on:
  push:
    branches:
      - lambda-functions  # lambda-functions 브랜치에서만 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Deploy Lambda Functions
      run: |
        echo "Deploying Lambda functions by folder..."

        # 각 폴더 이름과 Lambda 함수 이름 매핑
        declare -A FUNCTION_MAP=(
          ["FindPassword"]="FindPassword"
          ["LoginHistory_admin"]="LoginHistory_admin"
          ["FindUserId"]="FindUserId"
          ["NaverLogin"]="NaverLogin"
          ["RegisterRequest"]="RegisterRequest"
          ["CheckUserIdDuplicate"]="CheckUserIdDuplicate"
          ["DeleteReservation"]="DeleteReservation"
          ["NaverLoginCallback"]="NaverLoginCallback"
          ["ReturnUserInfo"]="ReturnUserInfo"
          ["ChangePassword"]="ChangePassword"
          ["FindPassword-ORM"]="FindPassword-ORM"
          ["reservation_latest"]="reservation_latest"
          ["Login"]="Login"
          ["reservationinfo"]="reservationinfo"
          ["mypage_checkpw"]="mypage_checkpw"
          ["mypage_change_pw"]="mypage_change_pw"
          ["mypage_Delete_Account"]="mypage_Delete_Account"
          ["LoginRequest"]="LoginRequest"
          ["FindPassword-query"]="FindPassword-query"
          ["sendSMS"]="sendSMS"
          ["admin_page"]="admin_page"
        )

        # 각 폴더에 대해 순회하며 배포
        for FOLDER in "${!FUNCTION_MAP[@]}"; do
          FUNCTION_NAME="${FUNCTION_MAP[$FOLDER]}"
          echo "Deploying $FUNCTION_NAME from folder $FOLDER"

          # 폴더 내 코드 압축
          cd "$FOLDER"
          zip -r "../${FUNCTION_NAME}.zip" . -x '*.git*' '*.github/*'
          cd ..

          # AWS Lambda 코드 업데이트
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file "fileb://${FUNCTION_NAME}.zip"

          echo "Deployed $FUNCTION_NAME"
          rm -f "${FUNCTION_NAME}.zip"  # 압축 파일 삭제
        done
