name: Deploy All Lambdas

on:
  push:
    branches:
      - lambda-functions  # 트리거 브랜치를 lambda-functions로 변경

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Install dependencies (Node.js project)
      run: |
        if [ -f "package.json" ]; then npm install; fi

    - name: Deploy All Lambda Functions
      run: |
        echo "Fetching all Lambda functions..."
        LAMBDAS=$(aws lambda list-functions --query 'Functions[].FunctionName' --output text)

        for FUNCTION in $LAMBDAS; do
          echo "Deploying $FUNCTION"

          # 배포를 위한 압축 파일 생성
          zip -r "${FUNCTION}.zip" . -x '*.git*' '*.github/*'

          # AWS Lambda 코드 업데이트
          aws lambda update-function-code \
            --function-name "$FUNCTION" \
            --zip-file "fileb://${FUNCTION}.zip"

          echo "Deployed $FUNCTION"
          rm -f "${FUNCTION}.zip"
        done

    - name: Cleanup
      run: rm -f *.zip
